### ISSUE TITLE
RuntimeError: Pandoc died with exitcode "83" during conversion: b'  File "filter.py", line 39\n    def resolve_url(url: str) -> str:\n 

### ISSUE THREAD

**Issue by bradyt** [xuhcc/beancount-docs#4]
Hi, I was trying to build locally, but after `pip3 install -r requirements.txt`, I get the following.

```
$ python3 crawl.py 
Found 32 documents
Processing https://docs.google.com/document/d/1RaondTJCS_IUPBHFNdT8oqFKJjVJDsfsn6JEjBG04eA/
Traceback (most recent call last):
  File "crawl.py", line 65, in <module>
    main()
  File "crawl.py", line 59, in main
    convert(document, output_path)
  File "/Users/alice/code/beancount-docs/export.py", line 125, in convert
    outputfile=output,
  File "/usr/local/lib/python3.7/site-packages/pypandoc/__init__.py", line 103, in convert_text
    outputfile=outputfile, filters=filters)
  File "/usr/local/lib/python3.7/site-packages/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "83" during conversion: b'  File "filter.py", line 39\n    def resolve_url(url: str) -> str:\n                       ^\nSyntaxError: invalid syntax\nError running filter filter.py:\nFilter returned error status 1\n'
```

**Comment by bradyt** [comment]
Hmm, is there something going on with pandoc itself using older python?

**Comment by xuhcc** [comment]
I think the `pypandoc` module picked the wrong pandoc binary.

**Comment by xuhcc** [comment]
`pip3 install -r requirements.txt` should install pandoc binary as `py-pandoc` package, but if you had pandoc already installed on you system, there might be a conflict. Can you try to install all dependencies from requirements.txt into virtualenv and run the crawler from there?

**Comment by bradyt** [comment]
Aha, that fixed it, thank you very much.

```
# From https://virtualenv.pypa.io/en/latest/,
pip3 install virtualenv
virtualenv bc
source bc/bin/activate

# Then,
pip3 install -r requirements.txt
python3 crawl.py
```

**Comment by xuhcc** [comment]
I mentioned virtualenv as recommended way in readme.
